models/User.php
<?php

namespace app\models;

use Yii;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property integer $isAdmin
 * @property string $photo
 *
 * @property Comment[] $comments
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['isAdmin'], 'integer'],
            [['name', 'email', 'password', 'photo'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
            'password' => 'Password',
            'isAdmin' => 'Is Admin',
            'photo' => 'Photo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['user_id' => 'id']);
    }

    public static function findIdentity($id)
    {
        return User::findOne($id);
    }
    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        // TODO: Implement getAuthKey() method.
    }

    public function validateAuthKey($authKey)
    {
        // TODO: Implement validateAuthKey() method.
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        // TODO: Implement findIdentityByAccessToken() method.
    }

    public static function findByEmail($email)
    {
        return User::find()->where(['email'=>$email])->one();
    }

    public function validatePassword($password)
    {
        return ($this->password == $password) ? true : false;
    }
    
    public function create()
    {
        return $this->save(false);
    }
    
    public function saveFromVk($uid, $name, $photo)
    {
        $user = User::findOne($uid);
        if($user)
        {
            return Yii::$app->user->login($user);
        }
        
        $this->id = $uid;
        $this->name = $name;
        $this->photo = $photo;
        $this->create();
        
        return Yii::$app->user->login($this);
    }

    public function getImage()
    {
        return $this->photo;
    }
}

controllers/AuthController.php
<?php

namespace app\controllers;

use app\models\LoginForm;
use app\models\SignupForm;
use app\models\User;
use Yii;
use yii\web\Controller;

class AuthController extends Controller
{

	public function actionLogin()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->goBack();
		}
		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout()
	{
		Yii::$app->user->logout();
		return $this->goHome();
	}

	public function actionSignup()
	{
		$model = new SignupForm();

		if(Yii::$app->request->isPost)
		{
			$model->load(Yii::$app->request->post());
			if($model->signup())
			{
				return $this->redirect(['auth/login']);
			}
		}

		return $this->render('signup', ['model'=>$model]);
	}

	public function actionTest()
	{
		$user = User::findOne(1);

		Yii::$app->user->logout();
		
		if(Yii::$app->user->isGuest)
		{
			echo 'Пользователь гость';
		}
		else
		{
			echo 'Пользователь Авторизован';
		}
	}
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Project;
use app\models\Category;
// use app\models\CommentForm;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Payment;

class SiteController extends Controller {

	public function behaviors() {
		return [
		];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	public function actionIndex() {
		$data = Project::getAll(6);
		$popular = Project::getPopular();
		$recent = Project::getRecent();
		$categories = Category::getAll();
		
		return $this->render('index',[
			'projects'=>$data['projects'],
			'pagination'=>$data['pagination'],
			'popular'=>$popular,
			'recent'=>$recent,
			'categories'=>$categories
		]);
	}

	public function actionProjects($id = null) {

		$data = ($id) ? Category::getProjectsByCategory($id) : Project::getAll(6);
		$categories = Category::getAll();
		
		return $this->render('projects',[
			'projects'=>$data['projects'],
			'pagination'=>$data['pagination'],
			'categories'=>$categories
		]);
	}

	public function actionView($id) {

		$project = Project::findOne($id);
		$popular = Project::getPopular();
		$recent = Project::getRecent();
		$categories = Category::getAll();
		$payment = new Payment();

		$project->viewedCounter();
		
		if(Yii::$app->request->isPost && !Yii::$app->user->isGuest){

			$payment->load(Yii::$app->request->post());

			$payment->user_id = Yii::$app->user->id;

			$payment->sum = Yii::$app->request->post()['Payment']['sum'];

			$payment->project_id = $project->id;
			$payment->date = date('Y-m-d');

			$payment->save();

			$project->recalc();

			return $this->redirect(['site/view','id'=>$id]);
		}

		return $this->render('single',[
			'project'=>$project,
			'popular'=>$popular,
			'recent'=>$recent,
			'categories'=>$categories,
			'payment'=>$payment,
		]);
	}

	public function actionCategory($id) {

		$data = Category::getProjectsByCategory($id);
		$popular = Project::getPopular();
		$recent = Project::getRecent();
		$categories = Category::getAll();
		
		return $this->render('category',[
			'projects'=>$data['projects'],
			'pagination'=>$data['pagination'],
			'popular'=>$popular,
			'recent'=>$recent,
			'categories'=>$categories
		]);
	}

}

views/partials/comment.php
<?php if(!empty($comments)):?>

    <?php foreach($comments as $comment):?>
        <div class="bottom-comment"><!--bottom comment-->
            <div class="comment-img">
                <img width="50" class="img-circle" src="<?= $comment->user->image; ?>" alt="">
            </div>

            <div class="comment-text">
                <a href="#" class="replay btn pull-right"> Replay</a>
                <h5><?= $comment->user->name;?></h5>

                <p class="comment-date">
                    <?= $comment->getDate();?>
                </p>


                <p class="para"><?= $comment->text; ?></p>
            </div>
        </div>
    <?php endforeach;?>

<?php endif;?>
<!-- end bottom comment-->

<?php if(!Yii::$app->user->isGuest):?>
    <div class="leave-comment"><!--leave comment-->
        <h4>Leave a reply</h4>
        <?php if(Yii::$app->session->getFlash('comment')):?>
            <div class="alert alert-success" role="alert">
                <?= Yii::$app->session->getFlash('comment'); ?>
            </div>
        <?php endif;?>
        <?php $form = \yii\widgets\ActiveForm::begin([
            'action'=>['site/comment', 'id'=>$article->id],
            'options'=>['class'=>'form-horizontal contact-form', 'role'=>'form']])?>
        <div class="form-group">
            <div class="col-md-12">
                <?= $form->field($commentForm, 'comment')->textarea(['class'=>'form-control','placeholder'=>'Write Message'])->label(false)?>
            </div>
        </div>
        <button type="submit" class="btn send-btn">Post Comment</button>
        <?php \yii\widgets\ActiveForm::end();?>
    </div><!--end leave comment-->
<?php endif;?>

views/partials/footer.php
	<!-- FOOTER BEGIN -->
	<footer>
		<div id="footer">
			<section class="bottom">
				<div class="inner">
					<div class="block_copyrights"><p>&copy; Copyright 2017. All Rights Reserved.</p></div>
				</div>
			</section>
		</div>
	</footer>
	<!-- FOOTER END -->

views/partials/header.php
<?php
use yii\helpers\Url;
?>
	<!-- HEADER BEGIN -->
<header>
		<div id="header">
			<section class="top">
				<div class="inner">
					<div class="block_top_menu">
						<nav>
							<ul>
								<li class=""><a href="<?= Url::toRoute(['/']) ?>">Главная</a></li>
								<li class=""><a href="<?= Url::toRoute(['/site/projects']) ?>">Проекты</a></li>
							</ul>
						</nav>
					</div>
					
					<div class="block_top_menu" style="float: right;">
						<nav>
							<ul>
								<?php if(Yii::$app->user->isGuest):?>
									<li><a href="<?= Url::toRoute(['/auth/login'])?>">Вход</a></li>
									<li><a href="<?= Url::toRoute(['/auth/signup'])?>">Регистрация</a></li>
								<?php else: ?>
									<?php if(Yii::$app->user->identity->isAdmin): ?>
										<li><a href="<?= Url::toRoute(['/admin'])?>">Админка</a></li>
									<?php endif ?>
									<li><a href="<?= Url::toRoute(['/user/my-projects'])?>">Мои проекты</a></li>
									<li><a href="<?= Url::toRoute(['/auth/logout'])?>">Выход <?= ' (' . Yii::$app->user->identity->name . ')' ?></a></li>
								<?php endif;?>
							</ul>
						</nav>
					</div>

					<div class="clearboth"></div>
				</div>
			</section>
			
			<section class="middle">
				<div class="inner">
					<!-- <div id="logo_top"><a href="index.html"><img src="images/logo_top.png" alt="Enterprise" title="Enterprise"></a></div> -->
					<center>
						<h1>KickBeginner</h1>
					</center>
				</div>
			</section>
			
		</div>
	</header>
	<!-- HEADER END -->

views/partials/item.php
<?php
use yii\helpers\Url;
?>
<?php foreach($projects as $project):?>
	<article class="post_type_4">
		<div class="feature">
			<div class="image">
				<a href="<?= Url::toRoute(['site/view', 'id'=>$project->id]);?>">
					<img class="item-img" src="<?= $project->getImage();?>" alt=""><span class="hover"></span>
				</a>
			</div>
		</div>
		
		<div class="content">
			<div class="info">
				<div class="date"><?= $project->getDate();?></div>
				<div class="stats">
					<div class="views"><?= (int)$project->viewed ?></div>
				</div>
			</div>
			
			<div class="title">
				<a href="<?= Url::toRoute(['site/view', 'id'=>$project->id]);?>"><?= $project->title ?></a>
			</div>
			
			<div class="line_1"></div>
		</div>
	</article>
<?php endforeach; ?>

views/partials/sidebar.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

if(isset($is_single) && $is_single){
	$procent = floor($project->collected_sum/$project->need_sum * 100) . '%';
}
?>
<div class="sidebar">
	<?php if(isset($is_single) && $is_single): ?>
		<aside>
		<div class="sidebar_title_1">Собранно</div>
			<div class="block_sidebar_latest_reviews">
				<div class="review">
					<div class="title"><?= $project->collected_sum ?> / <?= $project->need_sum ?></div>
					<div class="num"><?= $procent ?></div>
					<div class="progress"><div class="bar" style="width:<?= ($procent <= 100) ? $procent : '100%; background-color: rgb(51, 204, 205);' ?>"></div></div>
				</div>
			</div>
		</aside>
		
		<?php if(!Yii::$app->user->isGuest): ?>
			<aside>
				<div class="sidebar_title_1">Перевести деньги</div>
				<div class="block_leave_comment_1" style="padding-top: 0;">
					<div class="form">
						<?php $form = ActiveForm::begin(); ?>
							<div class="fields" style="float: none;">
								<div class="label">Сумма</div>
								<div class="field">
									<?= $form->field($payment, 'sum')->textInput(['class'=>'w_focus_mark required'])->label(false) ?>
								</div>
							</div>

							<?= Html::submitButton('<p class="general_button_type_3">Отправить</p>', ['class' => 'btn-pay' ]) ?>
						<?php ActiveForm::end(); ?>
					</div>
				</div>
			</aside>
		<?php else: ?>
			<aside>
				<div class="sidebar_title_1">Перевести деньги</div>
				<div class="block_leave_comment_1" style="padding-top: 0;">
					<p >Чтобы переводить деньги нужно авторизоваться</p>
					<a href="<?= Url::toRoute(['auth/login'])?>"><p class="general_button_type_3">Войти</p></a>
				</div>
			</aside>
		<?php endif ?>
	<?php endif ?>
	<aside>
		<div class="sidebar_title_1">Популярные посты</div>
		
		<div class="block_sidebar_popular_posts">
			<?php foreach($popular as $project):?>
				<article>
					<div class="image"><a href="<?= Url::toRoute(['site/view','id'=>$project->id]);?>"><img src="<?= $project->getImage();?>" width=86 height=66 style="object-fit: contain;" alt=""></a></div>
					
					<div class="content">
						<div class="title">
							<a href="<?= Url::toRoute(['site/view','id'=>$project->id]);?>"><?= $project->title?></a>
						</div>
						
						<div class="info">
							<div class="date"><?= $project->getDate();?></div>
						</div>
					</div>
				</article>
			<?php endforeach;?>
		</div>
	</aside>

	<aside>
		<div class="sidebar_title_1">Последние посты</div>
		
		<div class="block_sidebar_popular_posts">

			<?php foreach($recent as $project):?>
				<article>
					<div class="image"><a href="<?= Url::toRoute(['site/view','id'=>$project->id]);?>"><img src="<?= $project->getImage();?>" width=86 height=66 style="object-fit: contain;" alt=""></a></div>
					
					<div class="content">
						<div class="title">
							<a href="<?= Url::toRoute(['site/view','id'=>$project->id]);?>"><?= $project->title?></a>
						</div>
						
						<div class="info">
							<div class="date"><?= $project->getDate();?></div>
						</div>
					</div>
				</article>
			<?php endforeach;?>

		</div>
	</aside>
	<aside>
	<div class="sidebar_title_1">Категории</div>
		<div class="block_sidebar_most_commented">
			<?php foreach($categories as $category):?>
				<article>
					<a href="<?= Url::toRoute(['site/category','id'=>$category->id]);?>">
						<span class="num"><?= $category->getProjectsCount();?><span class="tail"></span></span>
						<span class="title"><?= $category->title?></span>
					</a>
				</article>
			<?php endforeach;?>

		</div>
	</aside>
</div>